language: python
python:
        - "3.5"
        - "3.6"
install:
        - "pip install -r requirements.txt -r dev-requirements.txt"
script:
        - "pytest --cov=three_games tests"
after_sucess:
        - codeclimate-test-reporter --token $CODECLIMATE_REPO_TOKEN
        - echo "Done"