name: build
on:
  push:
    branches:
      - master
    tags:
      - '!*' # Do not execute on tags
    paths:
      - .github/workflows/*
      - src/*
      - test/*
      # - '*.json'
      # - yarn.lock
  pull_request:
    paths:
      - '!*.MD'
jobs:
  Build_and_Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.13', '3.12', '3.11' ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt -r dev-requirements.txt

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: venv/bin/pytest --cov
          debug: true
